const Config = require("../config");
const fs = require("fs");

const {
  tlang,
  botpic,
  language,
  getString,
  toAudio,
  toPTT,
  toVideo,
  sync,
  syncgit,
  ffmpeg,
  TelegraPh,
  UploadFileUgu,
  UploadFileCatbox,
  webp2mp4File,
  fancy,
  randomfancy,
  styletext,
  isAdmin,
  isBotAdmin,
  createUrl,
  dare,
  truth,
  random_question,
  amount_of_questions,
  stickerCmdKey,
  checkUpdate,
  applyUpdate,
  restartBotProcess,
  listLanguages,
  getLangName,
  langText,
  tr,
  loadLangPack,
  reloadLocale,
  heroku,
  render,
  koyeb
} = require("./helpers");

const {
  unixTimestampSeconds,
  generateMessageTag,
  processTime,
  getBuffer,
  smdBuffer,
  fetchJson,
  smdJson,
  runtime,
  clockString,
  sleep,
  isUrl,
  getTime,
  formatDate,
  formatp,
  jsonformat,
  logic,
  generateProfilePicture,
  bytesToSize,
  getSizeMedia,
  parseMention,
  GIFBufferToVideoBuffer,
  smsg,
  callsg
} = require("./msg");

const {
  listall,
  strikeThrough,
  wingdings,
  vaporwave,
  typewriter,
  analucia,
  tildeStrikeThrough,
  underline,
  doubleUnderline,
  slashThrough,
  sparrow,
  heartsBetween,
  arrowBelow,
  crossAboveBelow,
  creepify,
  bubbles,
  mirror,
  squares,
  roundsquares,
  flip,
  tiny,
  createMap,
  serif_I,
  manga,
  ladybug,
  runes,
  serif_B,
  serif_BI,
  fancy1,
  fancy2,
  fancy3,
  fancy4,
  fancy5,
  fancy6,
  fancy7,
  fancy8,
  fancy9,
  fancy10,
  fancy11,
  fancy12,
  fancy13,
  fancy14,
  fancy15,
  fancy16,
  fancy17,
  fancy18,
  fancy19,
  fancy20,
  fancy21,
  fancy22,
  fancy23,
  fancy24,
  fancy25,
  fancy26,
  fancy27,
  fancy28,
  fancy29,
  fancy30,
  fancy31,
  fancy32,
  fancy33,
  randomStyle
} = require("./fonts");

const { sck1 } = require(__dirname + "/database/user");
const { sck } = require(__dirname + "/database/group");
const { alive } = require(__dirname + "/database/alive");
const {
  pg,
  dbs,
  groupdb,
  userdb,
  alivedb,
  bot_
} = require(__dirname + "/database");
const { cmd, smd, commands } = require(__dirname + "/plugins");
const {
  sendAnimeReaction,
  sendGImages,
  AudioToBlackVideo,
  textToLogoGenerator,
  photoEditor,
  updateProfilePicture,
  randomeFunfacts,
  getRandom,
  generateSticker,
  forwardMessage,
  plugins,
  audioEditor,
  send,
  react,
  note,
  sendWelcome,
  aitts
} = require("./actions");
const { handleChatbot, resetChatSession } = require("./chatbot");

function parsedJid(text = "") {
  return text.match(/[0-9]+(-[0-9]+|)(@g\.us|@s\.whatsapp\.net|@lid)/g) || [];
}

module.exports = {
  plugins,
  forwardMessage,
  updateProfilePicture,
  sendAnimeReaction,
  sendGImages,
  textToLogoGenerator,
  photoEditor,
  randomeFunfacts,
  AudioToBlackVideo,
  getRandom,
  generateSticker,
  audioEditor,
  send,
  react,
  note,
  sendWelcome,
  aitts,
  handleChatbot,
  resetChatSession,
  pg,
  dbs,
  bot_,
  alive,
  sck,
  smd,
  commands,
  sck1,
  tlang,
  botpic,
  language,
  getString,
  toAudio,
  toPTT,
  toVideo,
  sync,
  syncgit,
  checkUpdate,
  applyUpdate,
  restartBotProcess,
  listLanguages,
  getLangName,
  langText,
  tr,
  loadLangPack,
  reloadLocale,
  ffmpeg,
  TelegraPh,
  UploadFileUgu,
  UploadFileCatbox,
  webp2mp4File,
  fancy,
  randomfancy,
  styletext,
  isAdmin,
  isBotAdmin,
  createUrl,
  dare,
  truth,
  random_question,
  amount_of_questions,
  stickerCmdKey,
  heroku,
  render,
  koyeb,
  unixTimestampSeconds,
  generateMessageTag,
  processTime,
  getBuffer,
  smdBuffer,
  fetchJson,
  smdJson,
  runtime,
  clockString,
  sleep,
  isUrl,
  getTime,
  formatDate,
  formatp,
  jsonformat,
  logic,
  generateProfilePicture,
  bytesToSize,
  getSizeMedia,
  parseMention,
  GIFBufferToVideoBuffer,
  smsg,
  callsg,
  listall,
  strikeThrough,
  wingdings,
  vaporwave,
  typewriter,
  analucia,
  tildeStrikeThrough,
  underline,
  doubleUnderline,
  slashThrough,
  sparrow,
  heartsBetween,
  arrowBelow,
  crossAboveBelow,
  creepify,
  bubbles,
  mirror,
  squares,
  roundsquares,
  flip,
  tiny,
  createMap,
  serif_I,
  manga,
  ladybug,
  runes,
  serif_B,
  serif_BI,
  fancy1,
  fancy2,
  fancy3,
  fancy4,
  fancy5,
  fancy6,
  fancy7,
  fancy8,
  fancy9,
  fancy10,
  fancy11,
  fancy12,
  fancy13,
  fancy14,
  fancy15,
  fancy16,
  fancy17,
  fancy18,
  fancy19,
  fancy20,
  fancy21,
  fancy22,
  fancy23,
  fancy24,
  fancy25,
  fancy26,
  fancy27,
  fancy28,
  fancy29,
  fancy30,
  fancy31,
  fancy32,
  fancy33,
  randomStyle,
  addCommand: cmd,
  groupdb,
  userdb,
  alivedb,
  get prefix() {
    return global.prefix !== undefined
      ? global.prefix
      : Config.HANDLERS && !["null", "false", "empty"].includes(Config.HANDLERS)
        ? Config.HANDLERS[0]
        : "";
  },
  Config,
  setting: Config,
  stor: async () => JSON.parse(fs.readFileSync(__dirname + "/store.json", "utf8")),
  fancytext: (text, index) => listall(text)[index - 1],
  parsedJid,
  parseJid: parsedJid,
  getAdmin: async (client, msg) => {
    const metadata = await client.groupMetadata(msg.chat);
    const admins = [];
    for (const participant of metadata.participants) {
      if (participant.admin != null) admins.push(participant.id);
    }
    return admins;
  },
  isGroup: (jid) => jid.endsWith("@g.us"),
  parseurl: (url) =>
    url.match(
      /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&/=]*)/gi
    ),
  isInstaUrl: (url) =>
    /(?:(?:http|https):\/\/)?(?:www.)?(?:instagram.com|instagr.am|instagr.com)\/(\w+)/gim.test(url),
  isNumber: function isNumber() {
    const num = parseInt(this, 10);
    return typeof num === "number" && !isNaN(num);
  },
  yt: async () => [],
  wikimedia: async () => [],
  shazam: async () => ({ status: false, message: "Shazam API not configured." })
};
